# - platform: group
#   name: Office
#   entities:
#     - cover.office_left
#     - cover.office_right

- platform: group
  name: Master Bedroom Shades
  entities:
    - cover.master_bedroom_north_shades
    - cover.master_bedroom_south_shades
