# General configuration
homeassistant:
  customize: !include customize.yaml
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name
  time_zone: America/Los_Angeles
  unit_system: imperial

# Base configuration
automation: !include_dir_merge_list automations
config:
counter:
discovery:
frontend:
history:
http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem
image:
ios:
logbook:
lovelace: !include integrations/lovelace.yaml
map:
media_source:
mobile_app:
person:
recorder:
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
ssdp:
sun:
system_health:
timer: !include integrations/timer.yaml
updater:
zone: !include integrations/zone.yaml

# Integrations
binary_sensor: !include integrations/binary_sensor.yaml
cover: !include integrations/cover.yaml
group: !include groups.yaml
input_boolean: !include integrations/input_boolean.yaml
light: !include integrations/light.yaml
sensor: !include integrations/sensor.yaml
weather:
yeelight: !include integrations/yeelight.yaml
